CREATE TABLE [dbo].[Providers]
(
    PROV_ID NVARCHAR(18) NOT NULL PRIMARY KEY,
	PROV_NAME NVARCHAR(60) NOT NULL, 
	SITE_NAME NVARCHAR(60), 
	DEPARTMENT NVARCHAR(50),
	TEAM NVARCHAR(50),
	FTE float, 
	EPIC_STATUS NVARCHAR(12),
	
)
